# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2266270b1bc40a40c81e78abb6becc3abcb283191eac68b7d6eb6c898c96263423550ec8f074b35ead0b1a6dbd009eece2969a96eefec304514106274589ca72

test:
  secret_key_base: 499f298e1b6eafd9adc0d78c952a2f27474cdbf7db4cb8c514bf1537ad30417083fb55f3497a459df936f4dd9c0214b88c7f33a7bb057c7b880abd33b78017e2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
